#
# Base image
#
image:  java:8

#
# Link those containers for testing
#
services:
   # - docker
   # - mysql

#
# Will be called before each state
#
before_script:
   # Install and config docker
   # Needs to start runner as  --docker-privileged
   #- apt-get install curl -y 
   #- curl -fsSL https://get.docker.com/gpg | apt-key add -
   #- curl -fsSL https://get.docker.com/ | sh
   #- usermod -aG docker root
   #- eval "$(docker-machine env default)"
   #- service docker start
   #- docker info
   # Install SBT
   - echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
   - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
   - apt-get update -y
   - apt-get install sbt -y
   - sbt sbt-version

#
# Will be called one time (creates our image for all states)
#
#build_image:
#  script:


#
# Our stages are starting here
#
stages:
 # - build
  - test
 # - deploy

test:
  stage: test
  script:
    - cd implementation
    - sbt clean test
  only:
    - master

#deploy:
#  stage: deploy
#  script:
#    - ls
#    - cd implementation
#    - sbt docker:publishLocal
#    - ls
#  only:
#    - master

