image: java:8

before_script:
  # Install SBT
  - echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
  - apt-get update -y
  - apt-get install sbt -y
  - sbt sbt-version


stages:
 # - build
  - test
  - deploy


#job1:
#  stage: build
#  script:
#    - execute-script-for-job1
#  only:
#    - master
#  tags:
#    - docker


test:
  stage: test
  script:
    - cd implementation
    - sbt clean test
  only:
    - master

deploy:
  stage: deploy
  script:
    - ls
    - cd implementation
    - sbt docker:publishLocal
    - ls
  only:
    - master

