image: java:8

# Will be called before each state
# before_script:

# Will be called one time (creates our image for all states)
build_image:
  script:
   # Install and config docker
   - whoami
   - echo $USER
   #- apt-get install curl -y 
   #- curl -fsSL https://get.docker.com/ | sh
   #- docker-machine start default
   #- docker-machine regenerate-certs default
   #- eval "$(docker-machine env default)"
   #- docker info
   # Install SBT
   #- echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
   #- apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
   #- apt-get update -y
   #- apt-get install sbt -y
   #- sbt sbt-version
   - failasdf

stages:
 # - build
  - test
  - deploy

test:
  stage: test
  script:
    - cd implementation
    - sbt clean test
  only:
    - master

deploy:
  stage: deploy
  script:
    - ls
    - cd implementation
    - sbt docker:publishLocal
    - ls
  only:
    - master

